pipeline {
    agent any 
    
    environment {
        AWS_REGION = 'us-east-1' 
        AWS_ACCOUNT_ID = '300536313346' 
        ECR_REPO = 'shopping-cart-app'
        
        IMAGE_TAG = "${env.BUILD_ID}"
        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        
        stage('Build Docker Image') {
            steps {
                // FIX 2: This explicitly tells Jenkins to go into the "app" folder where your Dockerfile actually lives.
                dir('project-root/app') {
                    sh "docker build -t ${ECR_REPO}:${IMAGE_TAG} -t ${ECR_REPO}:latest ."
                }
            }
        }
        
        stage('Push to Amazon ECR') {
            steps {
                // Authenticates automatically using your EC2 IAM Role
                sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}"
                
                // Tags the image and pushes it to AWS
                sh "docker tag ${ECR_REPO}:${IMAGE_TAG} ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}"
                sh "docker tag ${ECR_REPO}:latest ${ECR_REGISTRY}/${ECR_REPO}:latest"
                sh "docker push ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}"
                sh "docker push ${ECR_REGISTRY}/${ECR_REPO}:latest"
            }
        }
        
        stage('Deploy Application') {
            steps {
                // Kills the old version and starts the new one
                sh """
                docker stop shopping-cart || true
                docker rm shopping-cart || true
                docker run -d --name shopping-cart -p 80:8080 ${ECR_REGISTRY}/${ECR_REPO}:latest
                """
            }
        }
    }
}
